### ISSUE TITLE
Kafka consumer (and producer) are hardcoded to connect to Kafka on localhost

### ISSUE THREAD

**Issue by petebachant** [boom-astro/boom#191]
If running in a container, at least the consumer will need to use Kafka's hostname (`broker` in the current default Docker Compose config, but should be able to point to the real ZTF stream).

Related to #184

**Comment by Theodlz** [comment]
> Maybe a new section in the config like `input_streams`?
> 
> ```yaml
> input_streams:
>   ztf:
>     host: localhost
>     port: ...
>     key: ${BOOM_ZTF_KAFKA_KEY} # If we can build in automated injection of env vars
>   lsst:
>     host: localhost
>   some-other-cool-one: ...
> ```
> 

I'm fine not calling the key kafka but only if we add some comment in there explaining that it refers to kafka instances, abstracting that info entirely isnt a good idea in my opinion, otherwise one does not even know what it's supposed to point to.

Auto ingestion of env variables would be awesome.

**Comment by petebachant** [comment]
> I'm fine not calling the key kafka but only if we add some comment in there explaining that it refers to kafka instances

We have Kafka output streams though, so perhaps it should be nested if we need to define configurations for those too?

```yaml
kafka:
  input_streams:
    ztf:
  output_streams:
    ztf:
```

or

```yaml
kafka:
  ztf:
    input_stream:
    output_stream:
  lsst:
```
